default_content_ui.settings:
  type: config_object
  label: 'Default Content UI Settings'
  mapping:
    bulk_export_types:
      type: sequence
      label: 'Bulk Export Types'
      sequence:
        type: string
        label: 'Entity Type'
    local_export_types:
      type: sequence
      label: 'Local Export Types'
      sequence:
        type: string
        label: 'Entity Type'
    bulk_export_reference_mode:
      type: boolean
      label: 'Bulk Export: Include Dependencies'
    local_export_reference_mode:
      type: boolean
      label: 'Local Export: Include Dependencies'

action.configuration.default_content_ui_export_action:*:
  type: action_configuration_default
  label: 'Export Default Content configuration'
