default_content_ui.settings:
  type: config_object
  label: 'Default content UI Settings'
  mapping:
    folder:
      type: string
      label: 'Export folder'
    safe:
      type: sequence
      label: 'Export List'
      sequence:
        type: string
        label: 'Entity Type'

